### ISSUE TITLE
Invalid capture name "_keyword.function"

### ISSUE THREAD

**Issue by agriffis** [p00f/alabaster.nvim#11]
I'm running nightly nvim and editing clojure files, and I get this message:

```
Error in decoration provider treesitter/highlighter.win:
Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 351:14. Invalid capture name "_keyword.function":
  (#any-of? @_keyword.function "fn" "fn*" "defn" "defn-")
             ^

stack traceback:
	[C]: in function '_ts_parse_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: in function 'get_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:188: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:488: in function 'for_each_tree'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:175: in function 'prepare_highlight_states'
	/usr/share/nvim/runtime
```

When I open `after/queries/clojure/highlights.scm` I also see these warnings:

![image](https://github.com/p00f/alabaster.nvim/assets/50637/1ae9ce64-ff9b-4ebe-a0f5-bed3b2e726cb)

Any idea what I should change to get this working?

**Comment by agriffis** [comment]
This looks related https://github.com/nvim-treesitter/nvim-treesitter/commit/03f650705c0c10f97b214ca4ecca3c25ff9bee7d

**Comment by p00f** [comment]
I'll fix this, sorry I haven't been using this theme myself for some time

**Comment by agriffis** [comment]
Thanks! I like this theme because it's minimal, but I'd consider switching to something else. What did you switch to?

**Comment by p00f** [comment]
https://git.sr.ht/~p00f/moduster.nvim - it's a port of https://protesilaos.com/emacs/modus-themes but slightly more minimal.

This is unlisted because I keep changing it, and sometimes I rewrite history.

Let me know if something doesn't work, it's been a while since I used clojure

**Comment by p00f** [comment]
this is fixed now

**Comment by agriffis** [comment]
Thanks!
