### ISSUE TITLE
Starting LSP disables colors on function names

### ISSUE THREAD

**Issue by grierson** [p00f/alabaster.nvim#13]
nvim: 10.1
treesitter: latest
alabaster.nvim: latest

Starting LSP removes function name colors.

### LSP off
Clojure
![image](https://github.com/user-attachments/assets/d4b5d3c3-f9a7-403f-9d76-e70895912a7e)
Lua
![image](https://github.com/user-attachments/assets/5abee6ac-b661-45bb-b163-0fc61f01987e)

### LSP on
Clojure
![image](https://github.com/user-attachments/assets/b9375da4-9335-4aa9-8612-4b43fdd78cda)
Lua
![image](https://github.com/user-attachments/assets/9930ccd9-a738-429a-beff-960ba67d9262)

**Comment by p00f** [comment]
You need to disable semantic highlights, see [`:h lsp-semantic-highlight`](https://neovim.io/doc/user/lsp.html#lsp-semantic-highlight)
